import { PROPERTY_IDS, HOTEL_IDS } from "./catalog.js";
/** Approved local application paths, never public domain authority. */
export const TEMPLATE_IDS = [
  "T1",
  "T2",
  "T3",
  "T4",
  "T5",
  "T6",
  "T7",
  "T8",
] as const;
export type TemplateId = (typeof TEMPLATE_IDS)[number];
export interface Route {
  route_id: string;
  route_key: string;
  route_path: string;
  template_id: TemplateId;
  category: string;
  supported_locales: readonly ["th", "en"];
  requires_consent: boolean;
  requires_human_handoff: boolean;
  data_requirement_level: string;
  prototype_only: true;
  mock_data: true;
  status: "prototype";
  content_key: string;
}
export const TEMPLATE_NAMES: Record<TemplateId, string> = {
  T1: "Welcome",
  T2: "Discovery",
  T3: "Detail",
  T4: "Request",
  T5: "Lili Reception",
  T6: "Intake",
  T7: "Operations / Status",
  T8: "Support / Governance",
};
export const ROUTES: readonly Route[] = [
  {
    route_id: "R01",
    route_key: "welcome",
    route_path: "/welcome",
    template_id: "T1",
    category: "reception",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "welcome",
  },
  {
    route_id: "R02",
    route_key: "explore",
    route_path: "/explore",
    template_id: "T1",
    category: "reception",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "explore",
  },
  {
    route_id: "R03",
    route_key: "language",
    route_path: "/language",
    template_id: "T1",
    category: "reception",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "language",
  },
  {
    route_id: "R04",
    route_key: "my_request",
    route_path: "/my-request",
    template_id: "T1",
    category: "reception",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "my_request",
  },
  {
    route_id: "R05",
    route_key: "condo",
    route_path: "/condo",
    template_id: "T2",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "condo",
  },
  {
    route_id: "R06",
    route_key: "rent",
    route_path: "/rent",
    template_id: "T2",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "rent",
  },
  {
    route_id: "R07",
    route_key: "buy",
    route_path: "/buy",
    template_id: "T2",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "buy",
  },
  {
    route_id: "R08",
    route_key: "projects",
    route_path: "/projects",
    template_id: "T2",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "projects",
  },
  {
    route_id: "R09",
    route_key: "bts_living",
    route_path: "/bts-living",
    template_id: "T2",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "bts_living",
  },
  {
    route_id: "R10",
    route_key: "luxury_homes",
    route_path: "/luxury-homes",
    template_id: "T2",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "luxury_homes",
  },
  {
    route_id: "R11",
    route_key: "shortlist",
    route_path: "/shortlist",
    template_id: "T2",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "shortlist",
  },
  {
    route_id: "R12",
    route_key: "property_detail",
    route_path: "/property/:property_id",
    template_id: "T3",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "mock_detail",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "property_detail",
  },
  {
    route_id: "R13",
    route_key: "request_viewing",
    route_path: "/request-viewing",
    template_id: "T4",
    category: "property",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "request_viewing",
  },
  {
    route_id: "R14",
    route_key: "hotel",
    route_path: "/hotel",
    template_id: "T2",
    category: "hospitality",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "hotel",
  },
  {
    route_id: "R15",
    route_key: "hotel_search",
    route_path: "/hotel/search",
    template_id: "T2",
    category: "hospitality",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "hotel_search",
  },
  {
    route_id: "R16",
    route_key: "hotel_detail",
    route_path: "/hotel/:hotel_id",
    template_id: "T3",
    category: "hospitality",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "mock_detail",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "hotel_detail",
  },
  {
    route_id: "R17",
    route_key: "stay_request",
    route_path: "/stay-request",
    template_id: "T4",
    category: "hospitality",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "stay_request",
  },
  {
    route_id: "R18",
    route_key: "airport_transfer",
    route_path: "/airport-transfer",
    template_id: "T2",
    category: "mobility",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "airport_transfer",
  },
  {
    route_id: "R19",
    route_key: "car_with_driver",
    route_path: "/car-with-driver",
    template_id: "T2",
    category: "mobility",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "car_with_driver",
  },
  {
    route_id: "R20",
    route_key: "private_driver",
    route_path: "/private-driver",
    template_id: "T2",
    category: "mobility",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "private_driver",
  },
  {
    route_id: "R21",
    route_key: "trip_details",
    route_path: "/trip-details",
    template_id: "T4",
    category: "mobility",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "trip_details",
  },
  {
    route_id: "R22",
    route_key: "pickup_details",
    route_path: "/pickup-details",
    template_id: "T4",
    category: "mobility",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "pickup_details",
  },
  {
    route_id: "R23",
    route_key: "bespoke_request",
    route_path: "/bespoke-request",
    template_id: "T4",
    category: "concierge",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "bespoke_request",
  },
  {
    route_id: "R24",
    route_key: "lifestyle",
    route_path: "/lifestyle",
    template_id: "T2",
    category: "concierge",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "lifestyle",
  },
  {
    route_id: "R25",
    route_key: "dining",
    route_path: "/dining",
    template_id: "T2",
    category: "concierge",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "dining",
  },
  {
    route_id: "R26",
    route_key: "wellness",
    route_path: "/wellness",
    template_id: "T2",
    category: "concierge",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "wellness",
  },
  {
    route_id: "R27",
    route_key: "local_assistance",
    route_path: "/local-assistance",
    template_id: "T2",
    category: "concierge",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "local_assistance",
  },
  {
    route_id: "R28",
    route_key: "tell_lili",
    route_path: "/lili/tell",
    template_id: "T5",
    category: "lili",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "tell_lili",
  },
  {
    route_id: "R29",
    route_key: "lili_reception",
    route_path: "/lili/reception",
    template_id: "T5",
    category: "lili",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "lili_reception",
  },
  {
    route_id: "R30",
    route_key: "requirements",
    route_path: "/lili/requirements",
    template_id: "T5",
    category: "lili",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "minimal",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "requirements",
  },
  {
    route_id: "R31",
    route_key: "contact_details",
    route_path: "/intake/contact",
    template_id: "T6",
    category: "intake",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "contact",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "contact_details",
  },
  {
    route_id: "R32",
    route_key: "consent",
    route_path: "/intake/consent",
    template_id: "T6",
    category: "intake",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: true,
    data_requirement_level: "consent",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "consent",
  },
  {
    route_id: "R33",
    route_key: "review_request",
    route_path: "/intake/review",
    template_id: "T6",
    category: "intake",
    supported_locales: ["th", "en"],
    requires_consent: true,
    requires_human_handoff: true,
    data_requirement_level: "review",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "review_request",
  },
  {
    route_id: "R34",
    route_key: "pending_review",
    route_path: "/status/pending",
    template_id: "T7",
    category: "operations",
    supported_locales: ["th", "en"],
    requires_consent: true,
    requires_human_handoff: true,
    data_requirement_level: "status",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "pending_review",
  },
  {
    route_id: "R35",
    route_key: "request_status",
    route_path: "/status/request",
    template_id: "T7",
    category: "operations",
    supported_locales: ["th", "en"],
    requires_consent: true,
    requires_human_handoff: true,
    data_requirement_level: "status",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "request_status",
  },
  {
    route_id: "R36",
    route_key: "human_handoff",
    route_path: "/status/handoff",
    template_id: "T7",
    category: "operations",
    supported_locales: ["th", "en"],
    requires_consent: true,
    requires_human_handoff: true,
    data_requirement_level: "status",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "human_handoff",
  },
  {
    route_id: "R37",
    route_key: "help_support",
    route_path: "/support",
    template_id: "T8",
    category: "support",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "help_support",
  },
  {
    route_id: "R38",
    route_key: "privacy_safety",
    route_path: "/privacy-safety",
    template_id: "T8",
    category: "governance",
    supported_locales: ["th", "en"],
    requires_consent: false,
    requires_human_handoff: false,
    data_requirement_level: "none",
    prototype_only: true,
    mock_data: true,
    status: "prototype",
    content_key: "privacy_safety",
  },
];
export function resolveRoute(path: string): Route | null {
  const exact = ROUTES.find((route) => route.route_path === path);
  if (exact) return exact;
  if (PROPERTY_IDS.some((id) => path === `/property/${id}`))
    return ROUTES.find((route) => route.route_id === "R12") ?? null;
  if (HOTEL_IDS.some((id) => path === `/hotel/${id}`))
    return ROUTES.find((route) => route.route_id === "R16") ?? null;
  return null;
}
export function concretePath(route: Route): string {
  return route.route_path
    .replace(":property_id", "mock-property-1")
    .replace(":hotel_id", "mock-hotel-1");
}
